pipeline {
  agent any

  tools {
    nodejs 'NodeJS 18' // make sure you have this Node version set up in Jenkins tools
  }

  environment {
    ALLURE_RESULTS = 'allure-results'
  }

  stages {
    stage('Checkout Code') {
      steps {
        git 'https://github.com/navneetqa26/API-Testing'
      }
    }

    stage('Install Dependencies') {
      steps {
        sh 'npm ci' // installs Cypress, Allure plugin, etc.
      }
    }

    stage('Run Cypress Tests') {
      steps {
        sh 'npx cypress run'
      }
    }

    stage('Generate Allure Report') {
      steps {
        sh 'npx allure generate allure-results --clean -o allure-report'
      }
    }

    stage('Publish Allure Report') {
      steps {
        allure([
          reportBuildPolicy: 'always',
          results: [[path: 'allure-results']]
        ])
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'allure-report/**', allowEmptyArchive: true
    }
  }
}
