pipeline {
  agent any

  stages {
    stage('Run Tests') {
      steps {
        sh 'npx cypress run' // or your test command
      }
    }

    stage('Generate Allure Report') {
      steps {
        sh 'npx allure generate allure-results --clean -o allure-report'
      }
    }

    stage('Publish Allure Report') {
      steps {
        allure([
          reportBuildPolicy: 'always',
          results: [[path: 'allure-results']]
        ])
      }
    }
  }
}
